//! The script renderer: `render(layout, config) -> Script`.
//!
//! This is the deep module of the app. Every Windows PowerShell 5.1 quirk, escaping rule,
//! step ordering and logging convention lives here so every feature gets them for free
//! (ADR-0001, ADR-0004, `docs/windows-behaviour.md`). Templates under
//! `src-tauri/templates/*.ps1.tmpl` are included at compile time and rendered output is
//! checked against golden files under `src-tauri/tests/golden/`.
//!
//! Two kinds of script come out of here:
//!
//! - The **probe**, read-only, rendered on every app start. It prints one JSON document
//!   on standard output and nothing else there, so it carries the `#Requires` line and
//!   the generated-by header but no `USER SETTINGS` block and no log: a log line would
//!   corrupt the JSON. Failures go to standard error with exit code 1.
//! - The **switch script** per layout, which arrives with the switch ticket and follows
//!   the full shape in `CODING_STANDARDS.md`.

/// Rendered script text, ready to be written to disk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Script {
    pub text: String,
}

const PROBE_TEMPLATE: &str = include_str!("../../templates/probe.ps1.tmpl");

/// The probe script. `rendered_at` lands in the header so a user can tell which app
/// start wrote the file; it is a parameter so golden tests stay stable.
pub fn render_probe(rendered_at: &str) -> Script {
    Script {
        text: PROBE_TEMPLATE.replace("{{RENDERED_AT}}", rendered_at),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;

    const RENDERED_AT: &str = "2026-09-09T14:32:05-05:00";

    fn golden_path(name: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("tests/golden")
            .join(name)
    }

    /// Line endings depend on the checkout (`.gitattributes` makes both files CRLF on
    /// Windows and LF elsewhere), so the comparison ignores them.
    fn normalise(text: &str) -> String {
        text.replace("\r\n", "\n")
    }

    #[test]
    fn the_probe_renders_to_its_golden_file() {
        let rendered = render_probe(RENDERED_AT).text;
        let golden = fs::read_to_string(golden_path("probe.ps1")).expect(
            "tests/golden/probe.ps1 is missing; run `cargo test -- --ignored write_golden_files`",
        );
        assert_eq!(
            normalise(&rendered),
            normalise(&golden),
            "the rendered probe differs from tests/golden/probe.ps1; if the change is intended, run `cargo test -- --ignored write_golden_files`"
        );
    }

    #[test]
    fn the_probe_starts_with_the_requires_line_and_header() {
        let text = render_probe(RENDERED_AT).text;
        let mut lines = text.lines();
        assert_eq!(lines.next(), Some("#Requires -Version 5.1"));
        assert_eq!(lines.next(), Some("# generated by layoutswap: probe"));
        assert_eq!(lines.next(), Some("# rendered 2026-09-09T14:32:05-05:00"));
        assert!(!text.contains("{{"), "every placeholder is filled");
    }

    /// Rewrites the golden files from the current templates. Run on purpose, then
    /// review the diff.
    #[test]
    #[ignore]
    fn write_golden_files() {
        fs::create_dir_all(golden_path("")).unwrap();
        fs::write(golden_path("probe.ps1"), render_probe(RENDERED_AT).text).unwrap();
    }
}
