#Requires -Version 5.1
# generated by layoutswap: capabilities
# rendered 2026-09-09T14:32:05-05:00
#
# Read-only. Reports what each active monitor declares it can do: its DDC-CI
# capabilities string as the monitor sent it, and the modes Windows lists for it,
# as one JSON document on standard output keyed by device path. Nothing else is
# printed there; failures go to standard error. The probe never reads this: a
# capabilities request takes seconds per monitor (docs/windows-behaviour.md), so the
# app runs this script on its own, after the probe, and keeps the result.
#
# Exit codes: 0 reported, 1 could not read the display configuration.

$ErrorActionPreference = 'Stop'
$ReadTimeoutPerMonitorMs = 10000   # the wait is this times the number of active monitors, for all of them together

$csharp = @'
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace LayoutswapCapabilities {
    [StructLayout(LayoutKind.Sequential)] public struct LUID { public uint Low; public int High; }
    [StructLayout(LayoutKind.Sequential)] public struct RATIONAL { public uint Num; public uint Den; }
    [StructLayout(LayoutKind.Sequential)] public struct PATH_SOURCE { public LUID adapterId; public uint id; public uint modeInfoIdx; public uint statusFlags; }
    [StructLayout(LayoutKind.Sequential)] public struct PATH_TARGET {
        public LUID adapterId; public uint id; public uint modeInfoIdx; public uint outputTechnology; public uint rotation;
        public uint scaling; public RATIONAL refreshRate; public uint scanLineOrdering; public int targetAvailable; public uint statusFlags; }
    [StructLayout(LayoutKind.Sequential)] public struct PATH_INFO { public PATH_SOURCE source; public PATH_TARGET target; public uint flags; }
    [StructLayout(LayoutKind.Explicit, Size = 64)] public struct MODE_INFO {
        [FieldOffset(0)]  public uint infoType;
        [FieldOffset(4)]  public uint id;
        [FieldOffset(8)]  public LUID adapterId;
        [FieldOffset(16)] public ulong u0; [FieldOffset(24)] public ulong u1; [FieldOffset(32)] public ulong u2;
        [FieldOffset(40)] public ulong u3; [FieldOffset(48)] public ulong u4; [FieldOffset(56)] public ulong u5;
    }
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] public struct TARGET_NAME {
        public uint type; public uint size; public LUID adapterId; public uint id;
        public uint flags; public uint outputTechnology; public ushort edidMfg; public ushort edidProd; public uint connectorInstance;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]  public string friendlyName;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string devicePath; }
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] public struct SOURCE_NAME {
        public uint type; public uint size; public LUID adapterId; public uint id;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string gdiName; }

    // One active monitor: the device path the app keys on, and the GDI name the
    // physical monitor handle and the mode list come from.
    public class ActiveMonitor { public string DevicePath; public string Gdi; }

    public static class Api {
        const uint QDC_ONLY_ACTIVE_PATHS = 2;
        [DllImport("user32.dll")] static extern int GetDisplayConfigBufferSizes(uint flags, out uint nPaths, out uint nModes);
        [DllImport("user32.dll")] static extern int QueryDisplayConfig(uint flags, ref uint nPaths, [Out] PATH_INFO[] paths, ref uint nModes, [Out] MODE_INFO[] modes, IntPtr topo);
        [DllImport("user32.dll")] static extern int DisplayConfigGetDeviceInfo(ref TARGET_NAME p);
        [DllImport("user32.dll")] static extern int DisplayConfigGetDeviceInfo(ref SOURCE_NAME p);

        public static List<ActiveMonitor> ActiveMonitors() {
            uint np, nm;
            int rc = GetDisplayConfigBufferSizes(QDC_ONLY_ACTIVE_PATHS, out np, out nm);
            if (rc != 0) throw new Exception("GetDisplayConfigBufferSizes failed with error " + rc);
            var paths = new PATH_INFO[np]; var modes = new MODE_INFO[nm];
            rc = QueryDisplayConfig(QDC_ONLY_ACTIVE_PATHS, ref np, paths, ref nm, modes, IntPtr.Zero);
            if (rc != 0) throw new Exception("QueryDisplayConfig failed with error " + rc);
            var found = new List<ActiveMonitor>();
            for (int i = 0; i < np; i++) {
                var p = paths[i];
                var t = new TARGET_NAME { type = 2, size = (uint)Marshal.SizeOf(typeof(TARGET_NAME)), adapterId = p.target.adapterId, id = p.target.id };
                var s = new SOURCE_NAME { type = 1, size = (uint)Marshal.SizeOf(typeof(SOURCE_NAME)), adapterId = p.source.adapterId, id = p.source.id };
                if (DisplayConfigGetDeviceInfo(ref t) != 0 || DisplayConfigGetDeviceInfo(ref s) != 0) continue;
                if (string.IsNullOrEmpty(t.devicePath) || string.IsNullOrEmpty(s.gdiName)) continue;
                found.Add(new ActiveMonitor { DevicePath = t.devicePath, Gdi = s.gdiName });
            }
            return found;
        }
    }

    // The HMONITOR Windows shows under a GDI name, as the probe finds it.
    public static class Monitors {
        [DllImport("user32.dll")] static extern bool EnumDisplayMonitors(IntPtr hdc, IntPtr clip, MonitorEnumProc proc, IntPtr data);
        [DllImport("user32.dll", CharSet = CharSet.Auto)] static extern bool GetMonitorInfo(IntPtr hMon, ref MONITORINFOEX mi);
        [StructLayout(LayoutKind.Sequential)] struct RECT { public int Left, Top, Right, Bottom; }
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]
        struct MONITORINFOEX { public int cbSize; public RECT rcMonitor, rcWork; public uint dwFlags; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string szDevice; }
        delegate bool MonitorEnumProc(IntPtr hMon, IntPtr hdc, ref RECT r, IntPtr d);

        public static IntPtr FindByGdi(string gdi) {
            IntPtr found = IntPtr.Zero;
            MonitorEnumProc cb = (IntPtr hMon, IntPtr hdc, ref RECT r, IntPtr d) => {
                var mi = new MONITORINFOEX { cbSize = Marshal.SizeOf(typeof(MONITORINFOEX)) };
                if (GetMonitorInfo(hMon, ref mi) && string.Equals(mi.szDevice.TrimEnd('\0'), gdi, StringComparison.OrdinalIgnoreCase)) found = hMon;
                return true; };
            EnumDisplayMonitors(IntPtr.Zero, IntPtr.Zero, cb, IntPtr.Zero);
            return found;
        }
    }

    // The DDC-CI capabilities string of the monitor under a GDI name. Each request runs
    // on its own thread and fills a record the caller already holds, and the script
    // waits once for every monitor together. The requests still take turns inside the
    // driver (three panels took about 13 s together on the reference machine, the same
    // as one after another), so the wait is sized per monitor and a monitor that never
    // answers costs its share and nothing more; its handle stays until the process
    // exits. A GDI name shared by several physical monitors (clone mode) cannot be
    // told apart and reads as not answered.
    public static class Caps {
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        struct PHYSICAL_MONITOR { public IntPtr h; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string desc; }
        [DllImport("dxva2.dll")] static extern bool GetNumberOfPhysicalMonitorsFromHMONITOR(IntPtr hMon, out uint n);
        [DllImport("dxva2.dll")] static extern bool GetPhysicalMonitorsFromHMONITOR(IntPtr hMon, uint n, [Out] PHYSICAL_MONITOR[] arr);
        [DllImport("dxva2.dll")] static extern bool DestroyPhysicalMonitors(uint n, PHYSICAL_MONITOR[] arr);
        [DllImport("dxva2.dll")] static extern bool GetCapabilitiesStringLength(IntPtr h, out uint len);
        [DllImport("dxva2.dll")] static extern bool CapabilitiesRequestAndCapabilitiesReply(IntPtr h, StringBuilder s, uint len);

        public class Reading { public bool Answered; public string Raw = ""; }

        static void ReadInto(string gdi, Reading r) {
            IntPtr hMon = Monitors.FindByGdi(gdi);
            if (hMon == IntPtr.Zero) return;
            uint n;
            if (!GetNumberOfPhysicalMonitorsFromHMONITOR(hMon, out n) || n != 1) return;
            var arr = new PHYSICAL_MONITOR[n];
            if (!GetPhysicalMonitorsFromHMONITOR(hMon, n, arr)) return;
            try {
                uint len;
                if (!GetCapabilitiesStringLength(arr[0].h, out len) || len == 0) return;
                var sb = new StringBuilder((int)len + 1);
                if (!CapabilitiesRequestAndCapabilitiesReply(arr[0].h, sb, len)) return;
                r.Raw = sb.ToString().TrimEnd('\0'); r.Answered = r.Raw.Trim().Length > 0;
            } finally { DestroyPhysicalMonitors(n, arr); }
        }

        public static Reading[] ReadAll(string[] gdis, int timeoutMs) {
            var results = new Reading[gdis.Length];
            var tasks = new System.Threading.Tasks.Task[gdis.Length];
            for (int i = 0; i < gdis.Length; i++) {
                string gdi = gdis[i]; var r = new Reading(); results[i] = r;
                tasks[i] = System.Threading.Tasks.Task.Factory.StartNew(() => ReadInto(gdi, r));
            }
            try { System.Threading.Tasks.Task.WaitAll(tasks, timeoutMs); } catch { }
            return results;
        }
    }

    // Every mode Windows lists for the monitor under a GDI name, as width, height and
    // the rounded refresh rate. Refresh rates are per mode, not per monitor
    // (docs/windows-behaviour.md); the app keeps the list without duplicates.
    public static class Modes {
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] public struct DEVMODE {
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string dmDeviceName;
            public ushort dmSpecVersion, dmDriverVersion, dmSize, dmDriverExtra;
            public uint dmFields;
            public int dmPositionX, dmPositionY; public uint dmDisplayOrientation, dmDisplayFixedOutput;
            public short dmColor, dmDuplex, dmYResolution, dmTTOption, dmCollate;
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string dmFormName;
            public ushort dmLogPixels; public uint dmBitsPerPel, dmPelsWidth, dmPelsHeight, dmDisplayFlags, dmDisplayFrequency;
            public uint dmICMMethod, dmICMIntent, dmMediaType, dmDitherType, dmReserved1, dmReserved2, dmPanningWidth, dmPanningHeight;
        }
        [DllImport("user32.dll", CharSet = CharSet.Unicode)] static extern bool EnumDisplaySettingsExW(string dev, uint iMode, ref DEVMODE dm, uint flags);

        public class Mode { public uint Width; public uint Height; public uint Hz; }

        public static List<Mode> List(string gdi) {
            var found = new List<Mode>();
            var dm = new DEVMODE(); dm.dmSize = (ushort)Marshal.SizeOf(typeof(DEVMODE));
            for (uint k = 0; EnumDisplaySettingsExW(gdi, k, ref dm, 0); k++) {
                // A frequency of 0 or 1 means the hardware default, not a rate.
                if (dm.dmPelsWidth == 0 || dm.dmPelsHeight == 0 || dm.dmDisplayFrequency < 2) continue;
                found.Add(new Mode { Width = dm.dmPelsWidth, Height = dm.dmPelsHeight, Hz = dm.dmDisplayFrequency });
            }
            return found;
        }
    }
}
'@
if (-not ([System.Management.Automation.PSTypeName]'LayoutswapCapabilities.Api').Type) {
    Add-Type -TypeDefinition $csharp -Language CSharp
}

try {
    $readAt = (Get-Date).ToString('o')
    $active = @([LayoutswapCapabilities.Api]::ActiveMonitors())
    $monitors = [ordered]@{}
    if ($active.Count -gt 0) {
        $readings = [LayoutswapCapabilities.Caps]::ReadAll([string[]]@($active | ForEach-Object { $_.Gdi }), $ReadTimeoutPerMonitorMs * $active.Count)
        for ($i = 0; $i -lt $active.Count; $i++) {
            $modes = @([LayoutswapCapabilities.Modes]::List($active[$i].Gdi) | ForEach-Object {
                [pscustomobject]@{ width = [int64]$_.Width; height = [int64]$_.Height; hz = [int64]$_.Hz }
            })
            $monitors[$active[$i].DevicePath] = [pscustomobject]@{
                answered = [bool]$readings[$i].Answered
                raw      = [string]$readings[$i].Raw
                modes    = $modes
            }
        }
    }
    $report = [pscustomobject]@{ readAt = $readAt; monitors = $monitors }
    [Console]::Out.Write(($report | ConvertTo-Json -Depth 6 -Compress))
    exit 0
} catch {
    [Console]::Error.WriteLine("capabilities failed: " + $_.Exception.Message)
    exit 1
}
