#Requires -Version 5.1
# generated by layoutswap: probe
# rendered 2026-09-09T14:32:05-05:00
#
# Read-only. Reports every monitor Windows knows about, the arrangement of the
# active ones as the raw display-config arrays, the GPU behind each, and the
# current input source of each active monitor over DDC-CI, as one JSON document
# on standard output. Nothing else is printed there; failures go to standard error.
# A monitor that does not answer DDC-CI within the timeout is reported as such.
#
# Exit codes: 0 reported, 1 could not read the display configuration.

$ErrorActionPreference = 'Stop'
$DdcTimeoutMs = 1500   # for every monitor together; silent monitors cost this much and no more

$csharp = @'
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace LayoutswapProbe {
    [StructLayout(LayoutKind.Sequential)] public struct LUID { public uint Low; public int High; }
    [StructLayout(LayoutKind.Sequential)] public struct RATIONAL { public uint Num; public uint Den; }
    [StructLayout(LayoutKind.Sequential)] public struct PATH_SOURCE { public LUID adapterId; public uint id; public uint modeInfoIdx; public uint statusFlags; }
    [StructLayout(LayoutKind.Sequential)] public struct PATH_TARGET {
        public LUID adapterId; public uint id; public uint modeInfoIdx; public uint outputTechnology; public uint rotation;
        public uint scaling; public RATIONAL refreshRate; public uint scanLineOrdering; public int targetAvailable; public uint statusFlags; }
    [StructLayout(LayoutKind.Sequential)] public struct PATH_INFO { public PATH_SOURCE source; public PATH_TARGET target; public uint flags; }

    // 64-byte DISPLAYCONFIG_MODE_INFO; the union is kept as raw 8-byte words and
    // overlaid with the source-mode fields we want to read (width/height/position).
    [StructLayout(LayoutKind.Explicit, Size = 64)] public struct MODE_INFO {
        [FieldOffset(0)]  public uint infoType;
        [FieldOffset(4)]  public uint id;
        [FieldOffset(8)]  public LUID adapterId;
        [FieldOffset(16)] public ulong u0; [FieldOffset(24)] public ulong u1; [FieldOffset(32)] public ulong u2;
        [FieldOffset(40)] public ulong u3; [FieldOffset(48)] public ulong u4; [FieldOffset(56)] public ulong u5;
        [FieldOffset(16)] public uint srcWidth; [FieldOffset(20)] public uint srcHeight;
        [FieldOffset(24)] public uint srcPixelFormat; [FieldOffset(28)] public int srcX; [FieldOffset(32)] public int srcY;
    }

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] public struct TARGET_NAME {
        public uint type; public uint size; public LUID adapterId; public uint id;
        public uint flags; public uint outputTechnology; public ushort edidMfg; public ushort edidProd; public uint connectorInstance;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]  public string friendlyName;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string devicePath; }
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] public struct ADAPTER_NAME {
        public uint type; public uint size; public LUID adapterId; public uint id;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string devicePath; }
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] public struct SOURCE_NAME {
        public uint type; public uint size; public LUID adapterId; public uint id;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string gdiName; }

    // One row per source-to-target path, every field already flattened so the
    // PowerShell side never edits a nested struct (see docs/windows-behaviour.md).
    public class PathRow {
        public bool Active; public bool Available; public bool HasMode;
        public string SourceAdapter; public string TargetAdapter; public string Monitor; public string Friendly; public string Gdi;
        public long TargetKey; public uint OutputTechnology; public uint ConnectorInstance; public uint Rotation;
        public uint RefreshNum; public uint RefreshDen; public int X, Y, W, H;
    }

    public class Snapshot {
        public PATH_INFO[] Paths; public MODE_INFO[] Modes; public PathRow[] Rows; public string[] ModeAdapter;
    }

    public static class Api {
        const uint QDC_ALL_PATHS = 1, QDC_ONLY_ACTIVE_PATHS = 2, PATH_ACTIVE = 1, IDX_INVALID = 0xFFFFFFFF;

        [DllImport("user32.dll")] static extern int GetDisplayConfigBufferSizes(uint flags, out uint nPaths, out uint nModes);
        [DllImport("user32.dll")] static extern int QueryDisplayConfig(uint flags, ref uint nPaths, [Out] PATH_INFO[] paths, ref uint nModes, [Out] MODE_INFO[] modes, IntPtr topo);
        [DllImport("user32.dll")] static extern int DisplayConfigGetDeviceInfo(ref TARGET_NAME p);
        [DllImport("user32.dll")] static extern int DisplayConfigGetDeviceInfo(ref ADAPTER_NAME p);
        [DllImport("user32.dll")] static extern int DisplayConfigGetDeviceInfo(ref SOURCE_NAME p);

        static string AdapterName(LUID id) {
            var a = new ADAPTER_NAME { type = 4, size = (uint)Marshal.SizeOf(typeof(ADAPTER_NAME)), adapterId = id };
            return DisplayConfigGetDeviceInfo(ref a) == 0 ? a.devicePath : "";
        }

        public static Snapshot Query(bool activeOnly) {
            uint flags = activeOnly ? QDC_ONLY_ACTIVE_PATHS : QDC_ALL_PATHS;
            uint np, nm;
            int rc = GetDisplayConfigBufferSizes(flags, out np, out nm);
            if (rc != 0) throw new Exception("GetDisplayConfigBufferSizes failed with error " + rc);
            var paths = new PATH_INFO[np]; var modes = new MODE_INFO[nm];
            rc = QueryDisplayConfig(flags, ref np, paths, ref nm, modes, IntPtr.Zero);
            if (rc != 0) throw new Exception("QueryDisplayConfig failed with error " + rc);
            Array.Resize(ref paths, (int)np); Array.Resize(ref modes, (int)nm);

            var snap = new Snapshot { Paths = paths, Modes = modes, Rows = new PathRow[np], ModeAdapter = new string[nm] };
            for (int i = 0; i < np; i++) {
                var p = paths[i];
                var r = new PathRow();
                r.Active = (p.flags & PATH_ACTIVE) != 0;
                r.Available = p.target.targetAvailable != 0;
                r.SourceAdapter = AdapterName(p.source.adapterId);
                r.TargetAdapter = AdapterName(p.target.adapterId);
                r.TargetKey = ((long)p.target.adapterId.High << 32) | p.target.adapterId.Low;
                r.TargetKey = (r.TargetKey * 1000003L) ^ p.target.id;
                var t = new TARGET_NAME { type = 2, size = (uint)Marshal.SizeOf(typeof(TARGET_NAME)), adapterId = p.target.adapterId, id = p.target.id };
                if (DisplayConfigGetDeviceInfo(ref t) == 0) { r.Monitor = t.devicePath; r.Friendly = t.friendlyName; r.OutputTechnology = t.outputTechnology; r.ConnectorInstance = t.connectorInstance; }
                else { r.Monitor = ""; r.Friendly = ""; r.OutputTechnology = p.target.outputTechnology; }
                var s = new SOURCE_NAME { type = 1, size = (uint)Marshal.SizeOf(typeof(SOURCE_NAME)), adapterId = p.source.adapterId, id = p.source.id };
                r.Gdi = (r.Active && DisplayConfigGetDeviceInfo(ref s) == 0) ? s.gdiName : "";
                r.Rotation = p.target.rotation; r.RefreshNum = p.target.refreshRate.Num; r.RefreshDen = p.target.refreshRate.Den;
                uint mi = p.source.modeInfoIdx;
                if (r.Active && mi != IDX_INVALID && mi < nm && modes[mi].infoType == 1) {
                    r.HasMode = true; r.W = (int)modes[mi].srcWidth; r.H = (int)modes[mi].srcHeight; r.X = modes[mi].srcX; r.Y = modes[mi].srcY;
                }
                snap.Rows[i] = r;
            }
            for (int j = 0; j < nm; j++) snap.ModeAdapter[j] = AdapterName(modes[j].adapterId);
            return snap;
        }

        static byte[] ToBytes<T>(T[] arr) {
            int sz = Marshal.SizeOf(typeof(T)); var buf = new byte[sz * arr.Length];
            var h = GCHandle.Alloc(buf, GCHandleType.Pinned);
            try { IntPtr p = h.AddrOfPinnedObject(); for (int i = 0; i < arr.Length; i++) Marshal.StructureToPtr(arr[i], new IntPtr(p.ToInt64() + i * sz), false); }
            finally { h.Free(); }
            return buf;
        }
        // Non-generic wrappers: Windows PowerShell 5.1 cannot call generic methods directly.
        public static byte[] PathsToBytes(PATH_INFO[] a) { return ToBytes<PATH_INFO>(a); }
        public static byte[] ModesToBytes(MODE_INFO[] a) { return ToBytes<MODE_INFO>(a); }
    }

    // The effective DPI of the monitor Windows shows under a GDI name, 0 when not found.
    // powershell.exe is not DPI-aware, and Windows answers 96 to such a process for
    // every monitor, so the process is made per-monitor aware first.
    public static class Dpi {
        [DllImport("user32.dll")] static extern bool SetProcessDpiAwarenessContext(IntPtr context);
        [DllImport("user32.dll")] static extern bool EnumDisplayMonitors(IntPtr hdc, IntPtr clip, MonitorEnumProc proc, IntPtr data);
        [DllImport("user32.dll", CharSet = CharSet.Auto)] static extern bool GetMonitorInfo(IntPtr hMon, ref MONITORINFOEX mi);
        [DllImport("shcore.dll")] static extern int GetDpiForMonitor(IntPtr hMon, int type, out uint dpiX, out uint dpiY);

        [StructLayout(LayoutKind.Sequential)] struct RECT { public int Left, Top, Right, Bottom; }
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]
        struct MONITORINFOEX { public int cbSize; public RECT rcMonitor, rcWork; public uint dwFlags; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string szDevice; }
        delegate bool MonitorEnumProc(IntPtr hMon, IntPtr hdc, ref RECT r, IntPtr d);

        // DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2; older Windows 10 builds refuse it, which is fine.
        public static void MakeAware() { try { SetProcessDpiAwarenessContext(new IntPtr(-4)); } catch { } }

        // The HMONITOR Windows shows under a GDI name, or zero when not found.
        public static IntPtr FindByGdi(string gdi) {
            IntPtr found = IntPtr.Zero;
            MonitorEnumProc cb = (IntPtr hMon, IntPtr hdc, ref RECT r, IntPtr d) => {
                var mi = new MONITORINFOEX { cbSize = Marshal.SizeOf(typeof(MONITORINFOEX)) };
                if (GetMonitorInfo(hMon, ref mi) && string.Equals(mi.szDevice.TrimEnd('\0'), gdi, StringComparison.OrdinalIgnoreCase)) found = hMon;
                return true; };
            EnumDisplayMonitors(IntPtr.Zero, IntPtr.Zero, cb, IntPtr.Zero);
            return found;
        }

        public static uint ForGdi(string gdi) {
            IntPtr found = FindByGdi(gdi);
            if (found == IntPtr.Zero) return 0;
            uint x, y;
            try { return GetDpiForMonitor(found, 0, out x, out y) == 0 ? x : 0; } catch { return 0; }
        }
    }

    // The current input source (VCP code 0x60) and power mode (VCP code 0xD6) of each
    // monitor under a GDI name, read over DDC-CI through its physical monitor handle.
    // Windows keeps a sleeping monitor Active, so the power mode is the only way to
    // tell that a send would be swallowed (docs/windows-behaviour.md). Every monitor's
    // reads start on their own thread and the probe waits once for all of them, so
    // silent monitors cost one timeout in total, not one each. Each thread fills a
    // record the caller already holds, field by field, so a monitor that answered the
    // input read and then hung on the power-mode read still reads as answered. A
    // read that never returns keeps its handle until the process exits; nothing can
    // cancel it. Only an active monitor has a GDI name, and a GDI name shared by
    // several physical monitors (clone mode) cannot be told apart, so it reads as
    // not answering rather than as a guess.
    public static class Ddc {
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        struct PHYSICAL_MONITOR { public IntPtr h; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string desc; }
        [DllImport("dxva2.dll")] static extern bool GetNumberOfPhysicalMonitorsFromHMONITOR(IntPtr hMon, out uint n);
        [DllImport("dxva2.dll")] static extern bool GetPhysicalMonitorsFromHMONITOR(IntPtr hMon, uint n, [Out] PHYSICAL_MONITOR[] arr);
        [DllImport("dxva2.dll")] static extern bool DestroyPhysicalMonitors(uint n, PHYSICAL_MONITOR[] arr);
        [DllImport("dxva2.dll")] static extern bool GetVCPFeatureAndVCPFeatureReply(IntPtr h, byte code, out uint type, out uint current, out uint max);
        const byte VCP_INPUT_SOURCE = 0x60;
        const byte VCP_POWER_MODE = 0xD6;

        public class Reading { public string Status = "notAnswering"; public uint Value; public bool PowerAnswered; public uint Power; }

        static void ReadInto(string gdi, Reading r) {
            IntPtr hMon = Dpi.FindByGdi(gdi);
            if (hMon == IntPtr.Zero) return;
            uint n;
            if (!GetNumberOfPhysicalMonitorsFromHMONITOR(hMon, out n) || n != 1) return;
            var arr = new PHYSICAL_MONITOR[n];
            if (!GetPhysicalMonitorsFromHMONITOR(hMon, n, arr)) return;
            try {
                uint t, cur, max;
                // The input first: it is the read every monitor with DDC-CI answers, and
                // the one the probe's status is about. The power mode is asked only of a
                // monitor that answered it, so a silent panel costs one call, not two.
                if (!GetVCPFeatureAndVCPFeatureReply(arr[0].h, VCP_INPUT_SOURCE, out t, out cur, out max)) return;
                // MCCS 2.2 puts the input in the low byte; a monitor that answers in the
                // high byte instead is read there rather than as input zero.
                uint low = cur & 0xFF, high = (cur >> 8) & 0xFF;
                r.Value = low != 0 ? low : high; r.Status = "answered";
                uint pt, pcur, pmax;
                if (GetVCPFeatureAndVCPFeatureReply(arr[0].h, VCP_POWER_MODE, out pt, out pcur, out pmax)) {
                    r.Power = pcur & 0xFF; r.PowerAnswered = true;
                }
            } finally { DestroyPhysicalMonitors(n, arr); }
        }

        public static Reading[] ReadAll(string[] gdis, int timeoutMs) {
            var results = new Reading[gdis.Length];
            var tasks = new System.Threading.Tasks.Task[gdis.Length];
            for (int i = 0; i < gdis.Length; i++) {
                string gdi = gdis[i]; var r = new Reading(); results[i] = r;
                tasks[i] = System.Threading.Tasks.Task.Factory.StartNew(() => ReadInto(gdi, r));
            }
            try { System.Threading.Tasks.Task.WaitAll(tasks, timeoutMs); } catch { }
            return results;
        }
    }
}
'@
if (-not ([System.Management.Automation.PSTypeName]'LayoutswapProbe.Api').Type) {
    Add-Type -TypeDefinition $csharp -Language CSharp
}

try {
    [LayoutswapProbe.Dpi]::MakeAware()
    $probedAt = (Get-Date).ToString('o')
    $all    = [LayoutswapProbe.Api]::Query($false)
    $active = [LayoutswapProbe.Api]::Query($true)

    # GPU friendly names, matched to an adapter device path through the PnP id.
    $gpus = @()
    try {
        $gpus = @(Get-CimInstance -ClassName Win32_VideoController | ForEach-Object {
            [pscustomobject]@{ Name = [string]$_.Name; Key = ([string]$_.PNPDeviceID).Replace('\', '#').ToLowerInvariant() }
        })
    } catch { }
    function Get-GpuName([string]$adapterPath) {
        $lower = $adapterPath.ToLowerInvariant()
        foreach ($g in $gpus) { if ($g.Key -and $lower.Contains($g.Key)) { return $g.Name } }
        return ''
    }

    # One monitor per target. Several paths can lead to one target; the active path,
    # when there is one, carries the mode and the GDI name.
    $byTarget = [ordered]@{}
    foreach ($r in $all.Rows) {
        if (-not $r.Monitor) { continue }
        $key = [string]$r.TargetKey
        if (-not $byTarget.Contains($key)) {
            $byTarget[$key] = [pscustomobject]@{
                devicePath = $r.Monitor; friendlyName = $r.Friendly; gdiName = ''
                adapterDevicePath = $r.TargetAdapter; gpuName = (Get-GpuName $r.TargetAdapter)
                outputTechnology = [int64]$r.OutputTechnology; connectorInstance = [int]$r.ConnectorInstance
                active = $false; available = [bool]$r.Available; hasMode = $false
                x = 0; y = 0; width = 0; height = 0; refreshNum = 0; refreshDen = 0; rotation = 0; dpi = 0
                inputSource = $null; powerMode = $null; ddcCi = 'notRead'
            }
        }
        $m = $byTarget[$key]
        if ($r.Available) { $m.available = $true }
        if ($r.Active) {
            $m.active = $true; $m.gdiName = $r.Gdi; $m.ddcCi = 'notAnswering'
            $m.refreshNum = [int64]$r.RefreshNum; $m.refreshDen = [int64]$r.RefreshDen; $m.rotation = [int]$r.Rotation
            if ($r.HasMode) { $m.hasMode = $true; $m.x = $r.X; $m.y = $r.Y; $m.width = $r.W; $m.height = $r.H }
            if ($r.Gdi) { $m.dpi = [int][LayoutswapProbe.Dpi]::ForGdi($r.Gdi) }
        }
    }

    # Every active monitor's input source and power mode, asked at once.
    $asked = @($byTarget.Values | Where-Object { $_.active -and $_.gdiName })
    if ($asked.Count -gt 0) {
        $readings = [LayoutswapProbe.Ddc]::ReadAll([string[]]@($asked | ForEach-Object { $_.gdiName }), $DdcTimeoutMs)
        for ($i = 0; $i -lt $asked.Count; $i++) {
            $asked[$i].ddcCi = [string]$readings[$i].Status
            if ($readings[$i].Status -eq 'answered') {
                $asked[$i].inputSource = [int64]$readings[$i].Value
                if ($readings[$i].PowerAnswered) { $asked[$i].powerMode = [int64]$readings[$i].Power }
            }
        }
    }

    $report = [pscustomobject]@{
        probedAt = $probedAt
        monitors = @($byTarget.Values)
        arrangement = [pscustomobject]@{
            paths          = [Convert]::ToBase64String([LayoutswapProbe.Api]::PathsToBytes($active.Paths))
            modes          = [Convert]::ToBase64String([LayoutswapProbe.Api]::ModesToBytes($active.Modes))
            sourceAdapters = @($active.Rows | ForEach-Object { $_.SourceAdapter })
            targetAdapters = @($active.Rows | ForEach-Object { $_.TargetAdapter })
            modeAdapters   = @($active.ModeAdapter)
        }
    }
    [Console]::Out.Write(($report | ConvertTo-Json -Depth 6 -Compress))
    exit 0
} catch {
    [Console]::Error.WriteLine("probe failed: " + $_.Exception.Message)
    exit 1
}
