#Requires -Version 5.1
# generated by layoutswap: switch to Desk return
# rendered 2026-09-09T14:32:05-05:00 with template version 5
#
# Self-contained: the interop code, the arrangement and the summary are embedded,
# so this file runs alone from a shortcut with the app closed. The app regenerates
# it when the template or the layout changes; do not edit it by hand.
#
# Steps: [1/5] Check monitors  [2/5] Apply arrangement  [3/5] Send HDMI 1 to KG241Y X1  [4/5] Send Input 0x1E to unknown monitor, then wait until unknown monitor is Available  [5/5] Verify
# Progress lines read "[step/of] status text" where status is running, done,
# failed, skipped or needs-you. A needs-you line repeats while the script waits
# for you, with the seconds left: every second for the app, every ten seconds in
# a console, and the log keeps every tenth. Every other line is log. Every line also lands in switch.log
# beside this script, with a timestamp. Re-running a script whose arrangement is
# already applied skips the apply with a log line and verifies. The layout's own
# steps sit around the apply; a validate-only run skips them.
#
# Switches: -Pause keeps the console open at the end (shortcuts pass it);
# -ValidateOnly checks and validates but applies nothing, then verifies what is on now.
#
# Exit codes: 0 applied, 1 could not apply, 2 needed a user action.

param(
    [switch]$Pause,
    [switch]$ValidateOnly
)

#-----------------------------------------------------------------------------
# USER SETTINGS
#-----------------------------------------------------------------------------
$LayoutName    = 'Desk return'
$LayoutId      = '0123456789abcdef0123456789abcdef'
$CapturedAt    = '2026-09-09T14:33:00-05:00'
$AppRoot       = 'C:\Users\example\AppData\Local\layoutswap'
$MonitorsOn    = @(
    'MSI MP165 E6 · USB-C DisplayPort 2'   # \\?\DISPLAY#MSI30E5#5&1a2b3c4d&0&UID8726#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
    'MSI MP165 E6 · USB-C DisplayPort 1'   # \\?\DISPLAY#MSI30E5#5&1a2b3c4d&0&UID8724#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
    'KG241Y X1'   # \\?\DISPLAY#ACR0EC4#5&1a2b3c4d&0&UID8448#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
    'Built-in display'   # \\?\DISPLAY#EDO4245#5&1a2b3c4d&0&UID8449#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
)
$MonitorsOff   = @(
    'VG34VQEL1A'   # \\?\DISPLAY#AUS343F#5&1a2b3c4d&0&UID8725#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
)
$DropWaitSeconds      = 5      # how long a send step waits for its monitor to drop
$AvailableWaitSeconds = 120    # how long a wait for a monitor to be Available lasts

#-----------------------------------------------------------------------------
# Embedded layout data (written by layoutswap at capture; never edited)
#-----------------------------------------------------------------------------
$ArrangementJson = @'
{
  "paths": "QUFB",
  "modes": "QkJC",
  "sourceAdapters": [
    "gpu-a",
    "gpu-a",
    "gpu-a",
    "gpu-a"
  ],
  "targetAdapters": [
    "gpu-a",
    "gpu-a",
    "gpu-a",
    "gpu-a"
  ],
  "modeAdapters": [
    "gpu-a",
    "gpu-a",
    "gpu-a",
    "gpu-a",
    "gpu-a",
    "gpu-a",
    "gpu-a",
    "gpu-a"
  ]
}
'@
$SummaryJson = @'
{
  "monitors": [
    {
      "devicePath": "\\\\?\\DISPLAY#MSI30E5#5&1a2b3c4d&0&UID8726#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}",
      "label": "MSI MP165 E6 · USB-C DisplayPort 2",
      "on": true,
      "x": 0,
      "y": -1080,
      "width": 1920,
      "height": 1080,
      "refreshHz": 60.0,
      "rotation": 0,
      "scalePercent": 100,
      "primary": false
    },
    {
      "devicePath": "\\\\?\\DISPLAY#MSI30E5#5&1a2b3c4d&0&UID8724#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}",
      "label": "MSI MP165 E6 · USB-C DisplayPort 1",
      "on": true,
      "x": -1920,
      "y": 0,
      "width": 1920,
      "height": 1080,
      "refreshHz": 60.0,
      "rotation": 0,
      "scalePercent": 100,
      "primary": false
    },
    {
      "devicePath": "\\\\?\\DISPLAY#ACR0EC4#5&1a2b3c4d&0&UID8448#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}",
      "label": "KG241Y X1",
      "on": true,
      "x": 0,
      "y": 0,
      "width": 1920,
      "height": 1080,
      "refreshHz": 60.0,
      "rotation": 0,
      "scalePercent": 100,
      "primary": true
    },
    {
      "devicePath": "\\\\?\\DISPLAY#EDO4245#5&1a2b3c4d&0&UID8449#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}",
      "label": "Built-in display",
      "on": true,
      "x": 1920,
      "y": 0,
      "width": 2560,
      "height": 1600,
      "refreshHz": 165.0,
      "rotation": 0,
      "scalePercent": 150,
      "primary": false
    },
    {
      "devicePath": "\\\\?\\DISPLAY#AUS343F#5&1a2b3c4d&0&UID8725#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}",
      "label": "VG34VQEL1A",
      "on": false,
      "x": 0,
      "y": 0,
      "width": 0,
      "height": 0,
      "refreshHz": null,
      "rotation": null,
      "scalePercent": null,
      "primary": false
    }
  ]
}
'@

#-----------------------------------------------------------------------------
$ErrorActionPreference = 'Stop'
# The app reads this output through a pipe as UTF-8; without this, monitor labels with
# a middle dot come through in the OEM code page and print as replacement characters.
try { [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding $false } catch { }
$ScriptDir     = Split-Path -Parent $MyInvocation.MyCommand.Path
$LogPath       = Join-Path $ScriptDir 'switch.log'
$LockPath      = Join-Path $AppRoot 'switch.lock'
$SettleSeconds          = 2      # Windows finishes an apply asynchronously; the after-steps and verify wait this long first
$DdcTimeoutMs           = 3000   # a send step's DDC-CI command gets this long to answer
$AvailableSettleSeconds = 3      # a monitor that just came back settles this long before the apply
$StepCount     = 5
$ApplyStep     = 2
$VerifyStep    = 5
$script:CurrentStep = 0
$script:CurrentStepName = ''

# Every line printed also lands in switch.log with a timestamp, so a run started
# from a shortcut can be checked afterwards.
function Write-Host {
    param([Parameter(Position = 0, ValueFromRemainingArguments = $true)]$Object, [ConsoleColor]$ForegroundColor, [switch]$NoNewline, [switch]$NoLog)
    $text = "$Object"
    if (-not $NoLog) { try { Add-Content -Path $LogPath -Value ("{0:yyyy-MM-dd HH:mm:ss}  {1}" -f (Get-Date), $text) -Encoding UTF8 } catch { } }
    if ($PSBoundParameters.ContainsKey('ForegroundColor')) { Microsoft.PowerShell.Utility\Write-Host $text -ForegroundColor $ForegroundColor -NoNewline:$NoNewline }
    else { Microsoft.PowerShell.Utility\Write-Host $text -NoNewline:$NoNewline }
}

# One stable line per status change; the app parses these and a person can read them.
# -Quiet keeps a repeated needs-you line out of the log.
function Write-Step([int]$step, [string]$status, [string]$text, [switch]$Quiet) {
    $script:CurrentStep = $step
    if ($status -eq 'running') { $script:CurrentStepName = $text }
    $color = switch ($status) { 'done' { 'Green' } 'failed' { 'Red' } 'skipped' { 'DarkGray' } 'needs-you' { 'Yellow' } default { 'Cyan' } }
    Write-Host ("[{0}/{1}] {2} {3}" -f $step, $StepCount, $status, $text) -ForegroundColor $color -NoLog:$Quiet
}

# A failure line says what to do next, then what went wrong, then the Windows error code.
function Write-Failure([string]$action, [string]$reason, [int]$code) {
    $text = '{0}: {1}; {2}' -f $script:CurrentStepName, $action, $reason
    if ($code -ne 0) { $text += (' (Windows error {0})' -f $code) }
    Write-Step $script:CurrentStep 'failed' $text
}

function Finish([int]$code) {
    if (Test-Path $LockPath) {
        try { $owner = Get-Content $LockPath -First 1 } catch { $owner = '' }
        if ($owner -eq "pid=$PID") { try { Remove-Item $LockPath -Force } catch { } }
    }
    Write-Host ("Exit code {0}" -f $code)
    if ($Pause) {
        Microsoft.PowerShell.Utility\Write-Host ""
        Microsoft.PowerShell.Utility\Write-Host "Press any key to close..." -ForegroundColor DarkGray
        try { [void][Console]::ReadKey($true) } catch { Start-Sleep -Seconds 15 }
    }
    exit $code
}

$csharp = @'
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace LayoutswapSwitch {
    [StructLayout(LayoutKind.Sequential)] public struct LUID { public uint Low; public int High; }
    [StructLayout(LayoutKind.Sequential)] public struct RATIONAL { public uint Num; public uint Den; }
    [StructLayout(LayoutKind.Sequential)] public struct PATH_SOURCE { public LUID adapterId; public uint id; public uint modeInfoIdx; public uint statusFlags; }
    [StructLayout(LayoutKind.Sequential)] public struct PATH_TARGET {
        public LUID adapterId; public uint id; public uint modeInfoIdx; public uint outputTechnology; public uint rotation;
        public uint scaling; public RATIONAL refreshRate; public uint scanLineOrdering; public int targetAvailable; public uint statusFlags; }
    [StructLayout(LayoutKind.Sequential)] public struct PATH_INFO { public PATH_SOURCE source; public PATH_TARGET target; public uint flags; }

    // 64-byte DISPLAYCONFIG_MODE_INFO; the union is kept as raw 8-byte words and
    // overlaid with the source-mode fields we want to read (width/height/position).
    [StructLayout(LayoutKind.Explicit, Size = 64)] public struct MODE_INFO {
        [FieldOffset(0)]  public uint infoType;
        [FieldOffset(4)]  public uint id;
        [FieldOffset(8)]  public LUID adapterId;
        [FieldOffset(16)] public ulong u0; [FieldOffset(24)] public ulong u1; [FieldOffset(32)] public ulong u2;
        [FieldOffset(40)] public ulong u3; [FieldOffset(48)] public ulong u4; [FieldOffset(56)] public ulong u5;
        [FieldOffset(16)] public uint srcWidth; [FieldOffset(20)] public uint srcHeight;
        [FieldOffset(24)] public uint srcPixelFormat; [FieldOffset(28)] public int srcX; [FieldOffset(32)] public int srcY;
    }

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] public struct TARGET_NAME {
        public uint type; public uint size; public LUID adapterId; public uint id;
        public uint flags; public uint outputTechnology; public ushort edidMfg; public ushort edidProd; public uint connectorInstance;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)]  public string friendlyName;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string devicePath; }
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] public struct ADAPTER_NAME {
        public uint type; public uint size; public LUID adapterId; public uint id;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string devicePath; }
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)] public struct SOURCE_NAME {
        public uint type; public uint size; public LUID adapterId; public uint id;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string gdiName; }

    // One row per path with every field flattened, so the PowerShell side never
    // edits a nested struct (see docs/windows-behaviour.md).
    public class PathRow {
        public bool Active; public bool Available; public bool HasMode;
        public string SourceAdapter; public string TargetAdapter; public string Monitor; public string Friendly; public string Gdi;
        public uint Rotation; public uint RefreshNum; public uint RefreshDen; public int X, Y, W, H;
    }

    public static class Api {
        const uint QDC_ALL_PATHS = 1, QDC_ONLY_ACTIVE_PATHS = 2, PATH_ACTIVE = 1, IDX_INVALID = 0xFFFFFFFF;
        const uint SDC_USE_SUPPLIED_DISPLAY_CONFIG = 0x20, SDC_VALIDATE = 0x40, SDC_APPLY = 0x80, SDC_SAVE_TO_DATABASE = 0x200, SDC_ALLOW_CHANGES = 0x400;

        [DllImport("user32.dll")] static extern int GetDisplayConfigBufferSizes(uint flags, out uint nPaths, out uint nModes);
        [DllImport("user32.dll")] static extern int QueryDisplayConfig(uint flags, ref uint nPaths, [Out] PATH_INFO[] paths, ref uint nModes, [Out] MODE_INFO[] modes, IntPtr topo);
        [DllImport("user32.dll")] static extern int SetDisplayConfig(uint nPaths, PATH_INFO[] paths, uint nModes, MODE_INFO[] modes, uint flags);
        [DllImport("user32.dll")] static extern int DisplayConfigGetDeviceInfo(ref TARGET_NAME p);
        [DllImport("user32.dll")] static extern int DisplayConfigGetDeviceInfo(ref ADAPTER_NAME p);
        [DllImport("user32.dll")] static extern int DisplayConfigGetDeviceInfo(ref SOURCE_NAME p);

        static string AdapterName(LUID id) {
            var a = new ADAPTER_NAME { type = 4, size = (uint)Marshal.SizeOf(typeof(ADAPTER_NAME)), adapterId = id };
            return DisplayConfigGetDeviceInfo(ref a) == 0 ? a.devicePath : "";
        }

        public static PathRow[] Query(bool activeOnly) {
            uint flags = activeOnly ? QDC_ONLY_ACTIVE_PATHS : QDC_ALL_PATHS;
            uint np, nm;
            int rc = GetDisplayConfigBufferSizes(flags, out np, out nm);
            if (rc != 0) throw new Exception("GetDisplayConfigBufferSizes failed with error " + rc);
            var paths = new PATH_INFO[np]; var modes = new MODE_INFO[nm];
            rc = QueryDisplayConfig(flags, ref np, paths, ref nm, modes, IntPtr.Zero);
            if (rc != 0) throw new Exception("QueryDisplayConfig failed with error " + rc);
            var rows = new PathRow[np];
            for (int i = 0; i < np; i++) {
                var p = paths[i];
                var r = new PathRow();
                r.Active = (p.flags & PATH_ACTIVE) != 0;
                r.Available = p.target.targetAvailable != 0;
                r.SourceAdapter = AdapterName(p.source.adapterId);
                r.TargetAdapter = AdapterName(p.target.adapterId);
                var t = new TARGET_NAME { type = 2, size = (uint)Marshal.SizeOf(typeof(TARGET_NAME)), adapterId = p.target.adapterId, id = p.target.id };
                if (DisplayConfigGetDeviceInfo(ref t) == 0) { r.Monitor = t.devicePath; r.Friendly = t.friendlyName; } else { r.Monitor = ""; r.Friendly = ""; }
                var s = new SOURCE_NAME { type = 1, size = (uint)Marshal.SizeOf(typeof(SOURCE_NAME)), adapterId = p.source.adapterId, id = p.source.id };
                r.Gdi = (r.Active && DisplayConfigGetDeviceInfo(ref s) == 0) ? s.gdiName : "";
                r.Rotation = p.target.rotation; r.RefreshNum = p.target.refreshRate.Num; r.RefreshDen = p.target.refreshRate.Den;
                uint mi = p.source.modeInfoIdx;
                if (r.Active && mi != IDX_INVALID && mi < nm && modes[mi].infoType == 1) {
                    r.HasMode = true; r.W = (int)modes[mi].srcWidth; r.H = (int)modes[mi].srcHeight; r.X = modes[mi].srcX; r.Y = modes[mi].srcY;
                }
                rows[i] = r;
            }
            return rows;
        }

        // Adapter LUIDs change on every boot; rewrite them from the saved adapter
        // device paths to whatever they are right now, then validate or apply.
        // Returns 0 on success, -1 when an adapter is missing (named in `missing`),
        // otherwise the SetDisplayConfig error code.
        public static int Apply(PATH_INFO[] paths, MODE_INFO[] modes, string[] srcAdapter, string[] tgtAdapter, string[] modeAdapter, out string missing, bool validateOnly) {
            var cur = Query(false);
            var map = new Dictionary<string, LUID>(StringComparer.OrdinalIgnoreCase);
            uint np, nm;
            GetDisplayConfigBufferSizes(QDC_ALL_PATHS, out np, out nm);
            var curPaths = new PATH_INFO[np]; var curModes = new MODE_INFO[nm];
            QueryDisplayConfig(QDC_ALL_PATHS, ref np, curPaths, ref nm, curModes, IntPtr.Zero);
            for (int i = 0; i < np && i < cur.Length; i++) {
                if (cur[i].SourceAdapter != "") map[cur[i].SourceAdapter] = curPaths[i].source.adapterId;
                if (cur[i].TargetAdapter != "") map[cur[i].TargetAdapter] = curPaths[i].target.adapterId;
            }
            var miss = new List<string>();
            for (int i = 0; i < paths.Length; i++) {
                LUID l;
                if (map.TryGetValue(srcAdapter[i], out l)) paths[i].source.adapterId = l; else if (!miss.Contains(srcAdapter[i])) miss.Add(srcAdapter[i]);
                if (map.TryGetValue(tgtAdapter[i], out l)) paths[i].target.adapterId = l; else if (!miss.Contains(tgtAdapter[i])) miss.Add(tgtAdapter[i]);
            }
            for (int j = 0; j < modes.Length; j++) { LUID l; if (map.TryGetValue(modeAdapter[j], out l)) modes[j].adapterId = l; }
            missing = string.Join(" ; ", miss.ToArray());
            if (miss.Count > 0) return -1;
            uint flags = SDC_USE_SUPPLIED_DISPLAY_CONFIG | SDC_ALLOW_CHANGES | (validateOnly ? SDC_VALIDATE : (SDC_APPLY | SDC_SAVE_TO_DATABASE));
            return SetDisplayConfig((uint)paths.Length, paths, (uint)modes.Length, modes, flags);
        }

        static T[] FromBytes<T>(byte[] buf) {
            int sz = Marshal.SizeOf(typeof(T)); var arr = new T[buf.Length / sz];
            var h = GCHandle.Alloc(buf, GCHandleType.Pinned);
            try { IntPtr p = h.AddrOfPinnedObject(); for (int i = 0; i < arr.Length; i++) arr[i] = (T)Marshal.PtrToStructure(new IntPtr(p.ToInt64() + i * sz), typeof(T)); }
            finally { h.Free(); }
            return arr;
        }
        // Non-generic wrappers: Windows PowerShell 5.1 cannot call generic methods directly.
        public static PATH_INFO[] BytesToPaths(byte[] b) { return FromBytes<PATH_INFO>(b); }
        public static MODE_INFO[] BytesToModes(byte[] b) { return FromBytes<MODE_INFO>(b); }
    }

    // The effective DPI of the monitor Windows shows under a GDI name, 0 when not found.
    public static class Dpi {
        [DllImport("user32.dll")] static extern bool SetProcessDpiAwarenessContext(IntPtr context);
        [DllImport("user32.dll")] static extern bool EnumDisplayMonitors(IntPtr hdc, IntPtr clip, MonitorEnumProc proc, IntPtr data);
        [DllImport("user32.dll", CharSet = CharSet.Auto)] static extern bool GetMonitorInfo(IntPtr hMon, ref MONITORINFOEX mi);
        [DllImport("shcore.dll")] static extern int GetDpiForMonitor(IntPtr hMon, int type, out uint dpiX, out uint dpiY);

        [StructLayout(LayoutKind.Sequential)] struct RECT { public int Left, Top, Right, Bottom; }
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]
        struct MONITORINFOEX { public int cbSize; public RECT rcMonitor, rcWork; public uint dwFlags; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string szDevice; }
        delegate bool MonitorEnumProc(IntPtr hMon, IntPtr hdc, ref RECT r, IntPtr d);

        public static void MakeAware() { try { SetProcessDpiAwarenessContext(new IntPtr(-4)); } catch { } }

        // The HMONITOR Windows shows under a GDI name, or zero when not found.
        public static IntPtr FindByGdi(string gdi) {
            IntPtr found = IntPtr.Zero;
            MonitorEnumProc cb = (IntPtr hMon, IntPtr hdc, ref RECT r, IntPtr d) => {
                var mi = new MONITORINFOEX { cbSize = Marshal.SizeOf(typeof(MONITORINFOEX)) };
                if (GetMonitorInfo(hMon, ref mi) && string.Equals(mi.szDevice.TrimEnd('\0'), gdi, StringComparison.OrdinalIgnoreCase)) found = hMon;
                return true; };
            EnumDisplayMonitors(IntPtr.Zero, IntPtr.Zero, cb, IntPtr.Zero);
            return found;
        }

        public static uint ForGdi(string gdi) {
            IntPtr found = FindByGdi(gdi);
            if (found == IntPtr.Zero) return 0;
            uint x, y;
            try { return GetDpiForMonitor(found, 0, out x, out y) == 0 ? x : 0; } catch { return 0; }
        }
    }

    // Sending an input source over DDC-CI (VCP code 0x60) to the monitor under a GDI
    // name, through its physical monitor handle. Only an active monitor has a GDI
    // name, which is why the console direction sends before the apply and the desk
    // direction after it (docs/windows-behaviour.md).
    public static class Ddc {
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        struct PHYSICAL_MONITOR { public IntPtr h; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string desc; }
        [DllImport("dxva2.dll", SetLastError = true)] static extern bool GetNumberOfPhysicalMonitorsFromHMONITOR(IntPtr hMon, out uint n);
        [DllImport("dxva2.dll", SetLastError = true)] static extern bool GetPhysicalMonitorsFromHMONITOR(IntPtr hMon, uint n, [Out] PHYSICAL_MONITOR[] arr);
        [DllImport("dxva2.dll", SetLastError = true)] static extern bool DestroyPhysicalMonitors(uint n, PHYSICAL_MONITOR[] arr);
        [DllImport("dxva2.dll", SetLastError = true)] static extern bool GetVCPFeatureAndVCPFeatureReply(IntPtr h, byte code, out uint type, out uint current, out uint max);
        [DllImport("dxva2.dll", SetLastError = true)] static extern bool SetVCPFeature(IntPtr h, byte code, uint value);
        const byte VCP_INPUT_SOURCE = 0x60;

        public class Outcome { public string Error = ""; public uint Before; public bool Sent; }

        // Reads the input the monitor shows, then sends the new one unless it is already
        // there, so re-running a script is a no-op with a log line. Error is empty on
        // success, else what went wrong.
        static Outcome SetInputNow(string gdi, uint value) {
            var o = new Outcome();
            IntPtr hMon = Dpi.FindByGdi(gdi);
            if (hMon == IntPtr.Zero) { o.Error = "monitor " + gdi + " not found"; return o; }
            uint n;
            if (!GetNumberOfPhysicalMonitorsFromHMONITOR(hMon, out n) || n == 0) { o.Error = "no physical monitor handle"; return o; }
            if (n != 1) { o.Error = "several physical monitors share " + gdi + " (clone mode)"; return o; }
            var arr = new PHYSICAL_MONITOR[n];
            if (!GetPhysicalMonitorsFromHMONITOR(hMon, n, arr)) { o.Error = "GetPhysicalMonitorsFromHMONITOR failed, Win32 error " + Marshal.GetLastWin32Error(); return o; }
            try {
                uint t, cur, max;
                if (GetVCPFeatureAndVCPFeatureReply(arr[0].h, VCP_INPUT_SOURCE, out t, out cur, out max)) {
                    uint low = cur & 0xFF, high = (cur >> 8) & 0xFF;
                    o.Before = low != 0 ? low : high;
                    if (o.Before == value) return o;
                }
                if (!SetVCPFeature(arr[0].h, VCP_INPUT_SOURCE, value)) { o.Error = "SetVCPFeature failed, Win32 error " + Marshal.GetLastWin32Error(); return o; }
                o.Sent = true;
                return o;
            } finally { DestroyPhysicalMonitors(n, arr); }
        }

        // The send on its own thread with a timeout: a monitor that never answers must
        // not hold the switch where nothing can cancel it.
        public static Outcome SetInput(string gdi, uint value, int timeoutMs) {
            var task = System.Threading.Tasks.Task.Factory.StartNew(() => SetInputNow(gdi, value));
            try { if (task.Wait(timeoutMs)) return task.Result; } catch { }
            var late = new Outcome();
            late.Error = "no answer over DDC-CI within " + timeoutMs + " ms";
            return late;
        }
    }
}
'@
if (-not ([System.Management.Automation.PSTypeName]'LayoutswapSwitch.Api').Type) {
    Add-Type -TypeDefinition $csharp -Language CSharp
}

#-----------------------------------------------------------------------------
# Helpers
#-----------------------------------------------------------------------------
function Get-Rows([bool]$activeOnly) { @([LayoutswapSwitch.Api]::Query($activeOnly)) }

# The live picture keyed by device path: one entry per monitor, the active path winning.
function Get-Live {
    $live = @{}
    foreach ($r in (Get-Rows $false)) {
        if (-not $r.Monitor) { continue }
        $key = $r.Monitor.ToLowerInvariant()
        if (-not $live.ContainsKey($key)) {
            $name = if ($r.Friendly) { $r.Friendly } else { 'Unnamed monitor' }
            $live[$key] = [pscustomobject]@{ name = $name; active = $false; available = $false; x = 0; y = 0; w = 0; h = 0; refresh = 0.0; rotation = 0; dpi = 0; gdi = '' }
        }
        $m = $live[$key]
        if ($r.Available) { $m.available = $true }
        if ($r.Active) {
            $m.active = $true; $m.gdi = $r.Gdi
            if ($r.RefreshDen -gt 0) { $m.refresh = [math]::Round($r.RefreshNum / $r.RefreshDen, 3) }
            $m.rotation = switch ([int]$r.Rotation) { 2 { 90 } 3 { 180 } 4 { 270 } default { 0 } }
            if ($r.HasMode) { $m.x = $r.X; $m.y = $r.Y; $m.w = $r.W; $m.h = $r.H }
            if ($r.Gdi) { $m.dpi = [int][LayoutswapSwitch.Dpi]::ForGdi($r.Gdi) }
        }
    }
    return $live
}

# Verify: compare what is on now to the summary. The on set and each on monitor's
# position and size must match; refresh, rotation and scale differences are warnings.
function Compare-Live($summary, $live) {
    $failures = @()
    $warnings = @()
    $known = @{}
    foreach ($m in $summary.monitors) {
        $key = $m.devicePath.ToLowerInvariant()
        $known[$key] = $true
        $isActive = $live.ContainsKey($key) -and $live[$key].active
        if ($m.on -and -not $isActive) { $failures += ("{0} is not on" -f $m.label); continue }
        if (-not $m.on -and $isActive) { $failures += ("{0} is on but should be off" -f $m.label); continue }
        if (-not $m.on) { continue }
        $l = $live[$key]
        if ($l.x -ne $m.x -or $l.y -ne $m.y) { $failures += ("{0} landed at {1},{2} instead of {3},{4}" -f $m.label, $l.x, $l.y, $m.x, $m.y) }
        if ($l.w -ne $m.width -or $l.h -ne $m.height) { $failures += ("{0} is {1}x{2} instead of {3}x{4}" -f $m.label, $l.w, $l.h, $m.width, $m.height) }
        if ($m.refreshHz -and [math]::Abs($l.refresh - $m.refreshHz) -gt 0.01) { $warnings += ("{0} runs at {1} Hz instead of {2} Hz" -f $m.label, $l.refresh, $m.refreshHz) }
        if ($null -ne $m.rotation -and $l.rotation -ne $m.rotation) { $warnings += ("{0} is rotated {1} instead of {2}" -f $m.label, $l.rotation, $m.rotation) }
        if ($m.scalePercent -and $l.dpi -gt 0) {
            $scale = [int][math]::Floor(($l.dpi * 100 + 48) / 96)   # same rounding as the app's probe
            if ($scale -ne $m.scalePercent) { $warnings += ("{0} is scaled {1}% instead of {2}%" -f $m.label, $scale, $m.scalePercent) }
        }
    }
    foreach ($key in $live.Keys) {
        if ($live[$key].active -and -not $known.ContainsKey($key)) { $failures += ("an extra monitor is on: {0}" -f $live[$key].name) }
    }
    return [pscustomobject]@{ failures = $failures; warnings = $warnings }
}

function Get-ApplyReason([int]$rc) {
    switch ($rc) {
        87   { 'invalid parameter, a monitor in the layout is probably not connected' }
        1610 { 'bad configuration' }
        31   { 'general failure' }
        default { "SetDisplayConfig returned $rc" }
    }
}

$ArrangeAgain = 'arrange the monitors in Windows Settings > Display, then save the layout again'

# Waits until every monitor in $monitors (device path in lower case to label) is
# Available, up to the layout's Available wait. Prints the band's two lines once, then
# a needs-you progress line with the seconds left: every second for the app, every ten
# seconds from a shortcut launch (-Pause), and the log keeps every tenth either way.
# $action is the physical action with {0} for the monitor names. With $settle, a wait
# that had to wait settles $AvailableSettleSeconds afterwards, for the apply that
# follows. Returns the keys still Absent at the end.
function Wait-Available([int]$row, [hashtable]$monitors, [string]$action, [bool]$settle) {
    function Get-Absent { return ,@($monitors.Keys | Where-Object { -not (Test-Available $_) }) }
    function Get-Names([string[]]$keys) { return (@($keys | ForEach-Object { $monitors[$_] }) -join ', ') }
    $absent = Get-Absent
    if ($absent.Count -eq 0) {
        Write-Host ("  {0}: Available" -f (Get-Names @($monitors.Keys)))
        return ,@()
    }
    $names = Get-Names $absent
    $band = ($action -f $names)
    Write-Host ($band.Substring(0, 1).ToUpper() + $band.Substring(1) + '.') -ForegroundColor Yellow
    Write-Host ("Waiting until {0} is Available" -f $names)
    $deadline = (Get-Date).AddSeconds($AvailableWaitSeconds)
    $waited = $false
    while ($true) {
        $absent = Get-Absent
        if ($absent.Count -eq 0 -or (Get-Date) -ge $deadline) { break }
        $waited = $true
        $names = Get-Names $absent
        $left = [int][math]::Ceiling(($deadline - (Get-Date)).TotalSeconds)
        $quiet = ($left % 10 -ne 0)
        if (-not $Pause -or -not $quiet) {
            Write-Step $row 'needs-you' (("Waiting until {0} is Available: " + $action + "; {1} s left of {2} s") -f $names, $left, $AvailableWaitSeconds) -Quiet:$quiet
        }
        Start-Sleep -Seconds 1
    }
    if ($absent.Count -eq 0 -and $waited) {
        Write-Host ("  {0}: Available" -f (Get-Names @($monitors.Keys)))
        if ($settle) { Write-Host "  settling"; Start-Sleep -Seconds $AvailableSettleSeconds }
    }
    return ,$absent
}

# Whether the monitor with this device path is Available right now: one display-config
# query, cheap enough to poll.
function Test-Available([string]$key) {
    foreach ($r in (Get-Rows $false)) {
        if ($r.Monitor -and $r.Monitor.ToLowerInvariant() -eq $key -and $r.Available) { return $true }
    }
    return $false
}

# A send step: send the input source to the monitor with this device path, then
# follow the wait rule. The monitor must be Active, its GDI name being how the
# physical monitor is found; otherwise the step is skipped with a log line. A command
# that fails stops the switch: the user picks the input on the monitor instead.
function Send-InputSource {
    param([int]$Row, [string]$Sentence, [string]$DevicePath, [string]$Label, [int]$Code, [string]$InputName, [string]$Wait, [string]$Side)
    $row = $Row; $sentence = $Sentence; $label = $Label; $inputName = $InputName; $wait = $Wait
    if ($ValidateOnly) { Write-Step $row 'skipped' ("{0}: validated only" -f $sentence); return }
    Write-Step $row 'running' $sentence
    $key = $DevicePath.ToLowerInvariant()
    $live = Get-Live
    if (-not ($live.ContainsKey($key) -and $live[$key].active -and $live[$key].gdi)) {
        Write-Step $row 'skipped' ("{0}: {1} is not Active" -f $sentence, $label)
        return
    }
    $outcome = [LayoutswapSwitch.Ddc]::SetInput($live[$key].gdi, [uint32]$Code, $DdcTimeoutMs)
    if ($outcome.Error) {
        Write-Failure ("press the input button on {0} to pick {1}, then switch again" -f $label, $inputName) ("could not send the input source ({0})" -f $outcome.Error) 0
        Finish 2
    }
    if (-not $outcome.Sent) {
        Write-Host ("  {0} already shows {1}" -f $label, $inputName)
        Write-Step $row 'done' $sentence
        return
    }
    Write-Host ("  {0}: {1} sent (was 0x{2:X2})" -f $label, $inputName, $outcome.Before)
    switch ($wait) {
        'drop' {
            $deadline = (Get-Date).AddSeconds($DropWaitSeconds)
            while ((Get-Date) -lt $deadline -and (Test-Available $key)) { Start-Sleep -Milliseconds 500 }
            if (Test-Available $key) { Write-Host ("  {0} still Available after {1} s; the apply turns it off" -f $label, $DropWaitSeconds) }
            else { Write-Host ("  {0} dropped" -f $label) }
        }
        'available' {
            $still = Wait-Available $row @{ $key = $label } 'press the input button on {0}, or turn the other device off' ($Side -eq 'before')
            if ($still.Count -gt 0) {
                Write-Failure ("press the input button on {0}, or turn the other device off, then switch again" -f $label) ("{0} not Available after {1} s" -f $label, $AvailableWaitSeconds) 0
                Finish 2
            }
        }
    }
    Write-Step $row 'done' $sentence
}

#=============================================================================
Write-Host ""
Write-Host ("=== Switch to {0} ===" -f $LayoutName) -ForegroundColor Cyan

# Only one switch at a time, from the app or from a shortcut. A lock that a crashed run
# left behind is cleared by hand; the message says where it is.
if (Test-Path $LockPath) {
    $lines = @(Get-Content $LockPath)
    $otherPid = if ($lines.Count -gt 0) { $lines[0] -replace '^pid=', '' } else { '?' }
    $other = if ($lines.Count -gt 1) { $lines[1] -replace '^layout=', '' } else { 'another layout' }
    Write-Host ("Wait for the switch to {0} to finish, then try again. If process {1} is no longer running, delete {2} first." -f $other, $otherPid, $LockPath) -ForegroundColor Yellow
    Finish 2
}
try {
    if (-not (Test-Path $AppRoot)) { New-Item -ItemType Directory -Path $AppRoot | Out-Null }
    Set-Content -Path $LockPath -Value @("pid=$PID", "layout=$LayoutName") -Encoding ASCII
} catch {
    Write-Host ("Check that {0} is writable, then try again; could not take the lock ({1})." -f $AppRoot, $_.Exception.Message) -ForegroundColor Yellow
    Finish 1
}

[LayoutswapSwitch.Dpi]::MakeAware()
$summary = ($SummaryJson | ConvertFrom-Json)
$arrangement = ($ArrangementJson | ConvertFrom-Json)

#-----------------------------------------------------------------------------
# [1] Check monitors: every on monitor must be Available, else stop and name the Absent ones.
#-----------------------------------------------------------------------------
Write-Step 1 'running' 'Check monitors'
try {
    $live = Get-Live
    $absent = @()
    $onLabels = @{}
    foreach ($m in $summary.monitors) {
        if (-not $m.on) { continue }
        $key = $m.devicePath.ToLowerInvariant()
        $onLabels[$key] = $m.label
        if ($live.ContainsKey($key) -and $live[$key].available) { Write-Host ("  {0}: Available" -f $m.label) }
        else { $absent += $key; Write-Host ("  {0}: Absent" -f $m.label) }
    }
    if ($absent.Count -gt 0) {
        # An Absent monitor may be showing another device, or be unplugged: wait for it.
        $waitFor = @{}
        foreach ($k in $absent) { $waitFor[$k] = $onLabels[$k] }
        $still = Wait-Available 1 $waitFor 'press the input button on {0}, or plug it in' $true
        if ($still.Count -gt 0) {
            $names = (@($still | ForEach-Object { $onLabels[$_] }) -join ', ')
            Write-Failure ("press the input button on {0}, or plug it in, then switch again" -f $names) ("Absent: {0}" -f $names) 0
            Finish 2
        }
        $live = Get-Live
    }
    Write-Step 1 'done' 'Check monitors'
} catch {
    Write-Failure 'try the switch again' ("could not read the monitors ({0})" -f $_.Exception.Message) 0
    Finish 1
}


#-----------------------------------------------------------------------------
# [$ApplyStep] Apply arrangement: remap GPU identifiers by device path, validate, then apply.
# Already applied is a no-op with a log line, so re-running a script is safe.
#-----------------------------------------------------------------------------
Write-Step $ApplyStep 'running' 'Apply arrangement'
try {
    $paths = [LayoutswapSwitch.Api]::BytesToPaths([Convert]::FromBase64String($arrangement.paths))
    $modes = [LayoutswapSwitch.Api]::BytesToModes([Convert]::FromBase64String($arrangement.modes))
    $missing = ''
    $rc = [LayoutswapSwitch.Api]::Apply($paths, $modes, [string[]]$arrangement.sourceAdapters, [string[]]$arrangement.targetAdapters, [string[]]$arrangement.modeAdapters, [ref]$missing, $true)
    if ($rc -eq -1) { Write-Failure 'save the layout again on this machine' ("the GPU it was captured on is not present: {0}" -f $missing) 0; Finish 1 }
    if ($rc -ne 0)  { Write-Failure $ArrangeAgain ("Windows rejected the arrangement before applying it, {0}" -f (Get-ApplyReason $rc)) $rc; Finish 1 }
    Write-Host "  validated"
    $already = Compare-Live $summary $live
    if ($ValidateOnly) {
        Write-Step $ApplyStep 'skipped' 'Apply arrangement: validated only, nothing applied'
    } elseif ($already.failures.Count -eq 0) {
        Write-Step $ApplyStep 'skipped' 'Apply arrangement: already applied'
    } else {
        $rc = [LayoutswapSwitch.Api]::Apply($paths, $modes, [string[]]$arrangement.sourceAdapters, [string[]]$arrangement.targetAdapters, [string[]]$arrangement.modeAdapters, [ref]$missing, $false)
        if ($rc -ne 0)  { Write-Failure ('try the switch again, and if it keeps failing ' + $ArrangeAgain) ("Windows could not apply the arrangement, {0}" -f (Get-ApplyReason $rc)) $rc; Finish 1 }
        Write-Host "  applied"
        Start-Sleep -Seconds $SettleSeconds
        Write-Step $ApplyStep 'done' 'Apply arrangement'
    }
} catch {
    Write-Failure 'try the switch again' ("could not apply the arrangement ({0})" -f $_.Exception.Message) 0
    Finish 1
}

#-----------------------------------------------------------------------------
# [3] Send HDMI 1 to KG241Y X1
#-----------------------------------------------------------------------------
Send-InputSource -Row 3 -Sentence 'Send HDMI 1 to KG241Y X1' -DevicePath '\\?\DISPLAY#ACR0EC4#5&1a2b3c4d&0&UID8448#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}' -Label 'KG241Y X1' -Code 17 -InputName 'HDMI 1' -Wait 'none' -Side 'after'

#-----------------------------------------------------------------------------
# [4] Send Input 0x1E to unknown monitor, then wait until unknown monitor is Available
#-----------------------------------------------------------------------------
Send-InputSource -Row 4 -Sentence 'Send Input 0x1E to unknown monitor, then wait until unknown monitor is Available' -DevicePath 'gone' -Label 'unknown monitor' -Code 30 -InputName 'Input 0x1E' -Wait 'available' -Side 'after'

#-----------------------------------------------------------------------------
# [$VerifyStep] Verify: read the arrangement back and compare it to the summary.
#-----------------------------------------------------------------------------
Write-Step $VerifyStep 'running' 'Verify'
try {
    $result = Compare-Live $summary (Get-Live)
    foreach ($w in $result.warnings) { Write-Host ("  warning: {0}" -f $w) -ForegroundColor Yellow }
    if ($result.failures.Count -gt 0) {
        Write-Failure $ArrangeAgain ($result.failures -join '; ') 0
        Finish 1
    }
    Write-Step $VerifyStep 'done' 'Verify'
} catch {
    Write-Failure 'try the switch again' ("could not verify the arrangement ({0})" -f $_.Exception.Message) 0
    Finish 1
}

Write-Host ("Switched to {0}." -f $LayoutName) -ForegroundColor Green
Finish 0
